### ISSUE TITLE
Using SoLoader crashes because phone complains the lib is 32-bit

### ISSUE THREAD

**Issue by molikto** [facebook/SoLoader#1]
Hello. We have a app only ships armabi-v7a binaries. And rely on other abi's legacy support. But we have this crash log:

```
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.p1.mobile.putong/lib-main/libsqlite3x.so" is 32-bit instead of 64-bit
    at java.lang.Runtime.load(Runtime.java:332)
    at java.lang.System.load(System.java:1069)
    at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:71)
    at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
    at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
    at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:247)
    at io.requery.android.database.sqlite.SQLiteDatabase.<clinit>(SQLiteDatabase.java:78)
    at com.p1.mobile.android.data.orm.DatabaseStore.db(DatabaseStore.java:111)
    at com.p1.mobile.android.data.orm.DatabaseStore.lambda$asyncFetch$52(DatabaseStore.java:334)
    at com.p1.mobile.android.data.orm.DatabaseStore.access$lambda$2(DatabaseStore.java)
    at com.p1.mobile.android.data.orm.DatabaseStore$$Lambda$3.run(DatabaseStore.java)
    at com.p1.mobile.android.app.Au.lambda$io$35(Au.java:183)
    at com.p1.mobile.android.app.Au.access$lambda$1(Au.java)
    at com.p1.mobile.android.app.Au$$Lambda$2.call(Au.java)
    at rx.Observable.unsafeSubscribe(Observable.java:8644)
    at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
    ... 7 more
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.p1.mobile.putong/lib-main/libsqlite3x.so" is 32-bit instead of 64-bit
    at java.lang.Runtime.load(Runtime.java:332)
    at java.lang.System.load(System.java:1069)
    at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:71)
    at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
    at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
    at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:247)
    at io.requery.android.database.sqlite.SQLiteDatabase.<clinit>(SQLiteDatabase.java:78)
    at com.p1.mobile.android.data.orm.DatabaseStore.db(DatabaseStore.java:111)
    at com.p1.mobile.android.data.orm.DatabaseStore.lambda$asyncFetch$52(DatabaseStore.java:334)
    at com.p1.mobile.android.data.orm.DatabaseStore.access$lambda$2(DatabaseStore.java)
    at com.p1.mobile.android.data.orm.DatabaseStore$$Lambda$3.run(DatabaseStore.java)
    at com.p1.mobile.android.app.Au.lambda$io$35(Au.java:183)
    at com.p1.mobile.android.app.Au.access$lambda$1(Au.java)
    at com.p1.mobile.android.app.Au$$Lambda$2.call(Au.java)
    at rx.Observable.unsafeSubscribe(Observable.java:8644)
    at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)

```

So using `lib-main` only happens if System loader failed. This error happens on a Lenovo z90-7 phone

**Comment by michalgr** [comment]
Hi, thanks for reporting !

Are you able to reproduce this on your device ? Is it 100% reproducible on that phone ?

In theory, android should spawn your app off 32bit zygote if the app contains only armv7 libs. Here obviously it does not do so. Are you sure you have no armv8 libs in your apk ? You can double check by checking output of `unzip -lv <path-to-your-apk> | grep 'lib/'` If there is at least one 64bit library Android will refuse to run in compatibility mode.

The scary alternative is that android did not unpack any libs and it fails to recognize that your app requires compatibility mode. Let's worry about that after we rule out existance of armv8 libs.

**Comment by johnou** [comment]
I suspect this is the same issue (hard crash on app bootstrap, see stacktrace below) for Facebook, Messenger, Groups and Pages. By rolling back to com.facebook.katana_98.0.0.18.70-41212249_minAPI15(armeabi-v7a)(280,360,400,420,480,560,640dpi)_apkmirror.com.apk this is no longer an issue.

http://www.gsmarena.com/wiko_fever_4g-7810.php (latest ROM V.31 ANDROID MARSHMALLOW, not rooted, also tried resetting to factory defaults and reflashing factory image).

```noformat
10-14 21:40:27.043 16433 16448 E AppStateLoggerExceptionHandler: Handing uncaught exception
10-14 21:40:27.043 16433 16448 E AppStateLoggerExceptionHandler: java.lang.UnsatisfiedLinkError: dlopen failed: "/mnt/expand/4d637921-b2a1-45d7-97b5-67d2d86ef8f2/user/0/com.facebook.katana/lib-main/libgnustl_shared.so" is 32-bit instead of 64-bit
10-14 21:40:27.043 16433 16448 E AppStateLoggerExceptionHandler:        at java.lang.Runtime.load(Runtime.java:332)
10-14 21:40:27.043 16433 16448 E AppStateLoggerExceptionHandler:        at java.lang.System.load(System.java:1069)
10-14 21:40:27.043 16433 16448 E AppStateLoggerExceptionHandler:        at com.facebook.soloader.DirectorySoSource.a(:5005)
10-14 21:40:27.043 16433 16448 E AppStateLoggerExceptionHandler:        at com.facebook.soloader.SoLoader.a(:4920)
10-14 21:40:27.043 16433 16448 E AppStateLoggerExceptionHandler:        at com.facebook.soloader.DirectorySoSource.a(:5002)
10-14 21:40:27.043 16433 16448 E AppStateLoggerExceptionHandler:        at com.facebook.soloader.SoLoader.a(:4920)
10-14 21:40:27.043 16433 16448 E AppStateLoggerExceptionHandler:        at com.facebook.soloader.SoLoader.b(:4862)
10-14 21:40:27.043 16433 16448 E AppStateLoggerExceptionHandler:        at com.facebook.soloader.SoLoader.a(:4976)
10-14 21:40:27.043 16433 16448 E AppStateLoggerExceptionHandler:        at com.facebook.xzdecoder.XzInputStream.<clinit>(:38690)
10-14 21:40:27.043 16433 16448 E AppStateLoggerExceptionHandler:        at com.facebook.sosource.XzsAssetSoSource$XzsUnpacker$XzsBackedInputDsoIterator.<init>(:35636)
10-14 21:40:27.043 16433 16448 E AppStateLoggerExceptionHandler:        at com.facebook.sosource.XzsAssetSoSource$XzsUnpacker.b(:5368)
10-14 21:40:27.043 16433 16448 E AppStateLoggerExceptionHandler:        at com.facebook.soloader.UnpackingSoSource.a(:5100)
10-14 21:40:27.043 16433 16448 E AppStateLoggerExceptionHandler:        at com.facebook.soloader.UnpackingSoSource.a(:5073)
10-14 21:40:27.043 16433 16448 E AppStateLoggerExceptionHandler:        at com.facebook.soloader.SoLoader.a(:4939)
10-14 21:40:27.043 16433 16448 E AppStateLoggerExceptionHandler:        at com.facebook.sosource.FbSoLoader.a(:4783)
10-14 21:40:27.043 16433 16448 E AppStateLoggerExceptionHandler:        at com.facebook.base.app.DelegatingApplication.a(:679)
10-14 21:40:27.043 16433 16448 E AppStateLoggerExceptionHandler:        at com.facebook.katana.app.FacebookApplication.b(:125)
10-14 21:40:27.043 16433 16448 E AppStateLoggerExceptionHandler:        at com.facebook.base.app.DelegatingApplication.c(:597)
10-14 21:40:27.043 16433 16448 E AppStateLoggerExceptionHandler:        at X$cr.run(:24588)
10-14 21:40:27.046  1629  1687 D SettingsInterface:  from settings cache , name = sms_default_application , value = com.android.mms
10-14 21:40:27.047  1629  1687 D Mms/Provider/Sms: query begin, uri = content://sms/1599, selection = null
10-14 21:40:27.048  1629  1687 D Mms/Provider/Sms: query end
10-14 21:40:27.048 16433 16448 E CatchMeIfYouCan: Uncaught exception in '<default>':
10-14 21:40:27.049 16433 16448 E CatchMeIfYouCan: java.lang.UnsatisfiedLinkError: dlopen failed: "/mnt/expand/4d637921-b2a1-45d7-97b5-67d2d86ef8f2/user/0/com.facebook.katana/lib-main/libgnustl_shared.so" is 32-bit instead of 64-bit
10-14 21:40:27.049 16433 16448 E CatchMeIfYouCan:       at java.lang.Runtime.load(Runtime.java:332)
10-14 21:40:27.049 16433 16448 E CatchMeIfYouCan:       at java.lang.System.load(System.java:1069)
10-14 21:40:27.049 16433 16448 E CatchMeIfYouCan:       at com.facebook.soloader.DirectorySoSource.a(:5005)
10-14 21:40:27.049 16433 16448 E CatchMeIfYouCan:       at com.facebook.soloader.SoLoader.a(:4920)
10-14 21:40:27.049 16433 16448 E CatchMeIfYouCan:       at com.facebook.soloader.DirectorySoSource.a(:5002)
10-14 21:40:27.049 16433 16448 E CatchMeIfYouCan:       at com.facebook.soloader.SoLoader.a(:4920)
10-14 21:40:27.049 16433 16448 E CatchMeIfYouCan:       at com.facebook.soloader.SoLoader.b(:4862)
10-14 21:40:27.049 16433 16448 E CatchMeIfYouCan:       at com.facebook.soloader.SoLoader.a(:4976)
10-14 21:40:27.049 16433 16448 E CatchMeIfYouCan:       at com.facebook.xzdecoder.XzInputStream.<clinit>(:38690)
10-14 21:40:27.049 16433 16448 E CatchMeIfYouCan:       at com.facebook.sosource.XzsAssetSoSource$XzsUnpacker$XzsBackedInputDsoIterator.<init>(:35636)
10-14 21:40:27.049 16433 16448 E CatchMeIfYouCan:       at com.facebook.sosource.XzsAssetSoSource$XzsUnpacker.b(:5368)
10-14 21:40:27.049 16433 16448 E CatchMeIfYouCan:       at com.facebook.soloader.UnpackingSoSource.a(:5100)
10-14 21:40:27.049 16433 16448 E CatchMeIfYouCan:       at com.facebook.soloader.UnpackingSoSource.a(:5073)
10-14 21:40:27.049 16433 16448 E CatchMeIfYouCan:       at com.facebook.soloader.SoLoader.a(:4939)
10-14 21:40:27.050 16433 16448 E CatchMeIfYouCan:       at com.facebook.sosource.FbSoLoader.a(:4783)
10-14 21:40:27.050 16433 16448 E CatchMeIfYouCan:       at com.facebook.base.app.DelegatingApplication.a(:679)
10-14 21:40:27.050 16433 16448 E CatchMeIfYouCan:       at com.facebook.katana.app.FacebookApplication.b(:125)
10-14 21:40:27.050 16433 16448 E CatchMeIfYouCan:       at com.facebook.base.app.DelegatingApplication.c(:597)
10-14 21:40:27.050 16433 16448 E CatchMeIfYouCan:       at X$cr.run(:24588)
10-14 21:40:27.050 16433 16448 E AndroidRuntime: FATAL EXCEPTION: EnsureDelegate
10-14 21:40:27.050 16433 16448 E AndroidRuntime: Process: com.facebook.katana, PID: 16433
10-14 21:40:27.050 16433 16448 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: "/mnt/expand/4d637921-b2a1-45d7-97b5-67d2d86ef8f2/user/0/com.facebook.katana/lib-main/libgnustl_shared.so" is 32-bit instead of 64-bit
10-14 21:40:27.050 16433 16448 E AndroidRuntime:        at java.lang.Runtime.load(Runtime.java:332)
10-14 21:40:27.050 16433 16448 E AndroidRuntime:        at java.lang.System.load(System.java:1069)
10-14 21:40:27.050 16433 16448 E AndroidRuntime:        at com.facebook.soloader.DirectorySoSource.a(:5005)
10-14 21:40:27.050 16433 16448 E AndroidRuntime:        at com.facebook.soloader.SoLoader.a(:4920)
10-14 21:40:27.050 16433 16448 E AndroidRuntime:        at com.facebook.soloader.DirectorySoSource.a(:5002)
10-14 21:40:27.050 16433 16448 E AndroidRuntime:        at com.facebook.soloader.SoLoader.a(:4920)
10-14 21:40:27.050 16433 16448 E AndroidRuntime:        at com.facebook.soloader.SoLoader.b(:4862)
10-14 21:40:27.050 16433 16448 E AndroidRuntime:        at com.facebook.soloader.SoLoader.a(:4976)
10-14 21:40:27.050 16433 16448 E AndroidRuntime:        at com.facebook.xzdecoder.XzInputStream.<clinit>(:38690)
10-14 21:40:27.050 16433 16448 E AndroidRuntime:        at com.facebook.sosource.XzsAssetSoSource$XzsUnpacker$XzsBackedInputDsoIterator.<init>(:35636)
10-14 21:40:27.050 16433 16448 E AndroidRuntime:        at com.facebook.sosource.XzsAssetSoSource$XzsUnpacker.b(:5368)
10-14 21:40:27.050 16433 16448 E AndroidRuntime:        at com.facebook.soloader.UnpackingSoSource.a(:5100)
10-14 21:40:27.050 16433 16448 E AndroidRuntime:        at com.facebook.soloader.UnpackingSoSource.a(:5073)
10-14 21:40:27.050 16433 16448 E AndroidRuntime:        at com.facebook.soloader.SoLoader.a(:4939)
10-14 21:40:27.050 16433 16448 E AndroidRuntime:        at com.facebook.sosource.FbSoLoader.a(:4783)
10-14 21:40:27.050 16433 16448 E AndroidRuntime:        at com.facebook.base.app.DelegatingApplication.a(:679)
10-14 21:40:27.050 16433 16448 E AndroidRuntime:        at com.facebook.katana.app.FacebookApplication.b(:125)
10-14 21:40:27.050 16433 16448 E AndroidRuntime:        at com.facebook.base.app.DelegatingApplication.c(:597)
10-14 21:40:27.050 16433 16448 E AndroidRuntime:        at X$cr.run(:24588)
10-14 21:40:27.063   922   939 V ztgl    : asset != NULL
10-14 21:40:27.065   922   939 V ztgl    : asset != NULL
10-14 21:40:27.066   922 16479 W AES     : Exception Log handling...
10-14 21:40:27.067   922 16479 D AES     : ExceptionLog: notify aed
10-14 21:40:27.067   922 16479 D AES     :     process : com.facebook.katana
10-14 21:40:27.067   922 16479 D AES     :      module : com.facebook.katana v41551395 (99.0.0.16.69)
10-14 21:40:27.067   922 16479 D AES     :
10-14 21:40:27.067   922 16479 D AES     :       cause : data_app_crash
10-14 21:40:27.067   922 16479 D AES     :       pid : 16433
10-14 21:40:27.067   922   939 V ztgl    : asset != NULL
10-14 21:40:27.067   922 16479 D AEE/LIBAEE: shell: raise_exp(4, 16433, -1361051648, com.facebook.katana, 0x0x7f797bf640, 0x0x0)
10-14 21:40:27.067   922 16479 D AEE/LIBAEE: shell: connected with AED OK
```

**Comment by molikto** [comment]
There is no way to reproduce it. This is a stack trace from online bug reporting. Our app has a big installation number, and this crash only happens very rarely.

**Comment by johnou** [comment]
I can reproduce it 100% I took this stacktrace from adb logcat, feel free to reach out to me if you'd like to resolve it.

**Comment by rspencer01** [comment]
This appears to be due to this line. https://github.com/facebook/SoLoader/blob/master/java/com/facebook/soloader/SysUtil.java#L125. I am looking into changing it.

**Comment by iegik** [comment]
It happens with x64 chips like KIRIN 950, KIRIN 955 and Exynos 7420:
https://it.wikipedia.org/wiki/HiSilicon#KIRIN_950
Huawei Mate 8, Honor 8, Honor V8 (KNT-AL10, KNT-TL10)
Huawei P9, Huawei P9 Plus, Honor V8 (KNT-AL20), Honor Note 8

https://ru.wikipedia.org/wiki/Exynos
Galaxy S6 Edge (zerolte),

Platform armeabi-v7a

**Comment by iegik** [comment]
Both is with 8 CPU

**Comment by rspencer01** [comment]
I did submit a patch when I was with facebook.  @michalgr , will it be published?

**Comment by passy** [comment]
This is now in master with https://github.com/facebook/SoLoader/commit/c3b57fae6abdca24ee40b7f1e5b4ac34d8926be0
