### ISSUE TITLE
dso_lock: open failed: EACCES (Permission denied)

### ISSUE THREAD

**Issue by kaarthicksiyer** [facebook/SoLoader#120]
We are using react native to implement one of the modules in our app. Currently we are experiencing a weird behaviour in only some of the devices like Google pixel and Samsung A7 running on Android 12 onwards. We cannot seem to access the react native screens because of the following error:

`Fatal Exception: java.lang.RuntimeException: java.io.FileNotFoundException: /data/user/0/APP_ID/lib-0/dso_lock: open failed: EACCES (Permission denied)
       at com.facebook.soloader.SoLoader.init(SoLoader.java:219)
       at androidx.fragment.app.Fragment.performAttach(Fragment.java:3063)
       at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:464)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:254)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2985)
       at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:2909)
       at androidx.fragment.app.Fragment.performResume(Fragment.java:3189)
       at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:606)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
       at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1729)
       at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:323)
       at androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:249)
       at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
       at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:669)
       at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:631)
       at androidx.viewpager.widget.ViewPager.setCurrentItem(ViewPager.java:623)
       at com.google.android.material.navigation.NavigationBarView$1.onMenuItemSelected(NavigationBarView.java:291)
       at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:836)
       at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:159)
       at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:987)
       at com.google.android.material.navigation.NavigationBarMenuView$1.onClick(NavigationBarMenuView.java:139)
       at android.view.View.performClick(View.java:7870)
       at android.view.View.performClickInternal(View.java:7839)
       at android.view.View.access$3600(View.java:886)
       at android.view.View$PerformClick.run(View.java:29363)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7948)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)`

This is our react native dependencies:
dependencies": {
    "@babel/core": "^7.11.1",
    "@babel/runtime": "^7.11.2",
    "@react-native-community/masked-view": "0.1.10",
    "expo": "^38.0.0",
    "moment": "2.27.0",
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-gesture-handler": "1.7.0",
    "react-native-htmlview": "0.12.1",
    "react-native-image-placeholder": "1.0.14",
    "react-native-maps": "0.26.1",
    "react-native-reanimated": "1.13.0",
    "react-native-safe-area-context": "3.1.6",
    "react-native-screens": "2.10.1",
    "react-native-snap-carousel": "3.9.1",
    "react-native-tab-view": "2.15.1",
    "react-navigation": "4.4.0",
    "react-navigation-stack": "2.8.2",
    "react-navigation-tabs": "2.9.0",
    "@react-native-community/netinfo": "5.9.6",
    "@react-native-community/geolocation": "2.0.2"
  }

**Comment by DeveloperTecpinion** [comment]
Same issue in android 10..Tried all google solution..

**Comment by DeveloperTecpinion** [comment]
Can you please share any solution..Thanks in advance
