### ISSUE TITLE
android.os.strictmode.DiskReadViolation crash on app start

### ISSUE THREAD

**Issue by SaraTalaat91** [facebook/SoLoader#126]
Hi, after updating to latest version of SoLoader (0.11.0), app started to crash on launch with this exception

``` 
Caused by android.os.strictmode.DiskReadViolation:
       at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
       at libcore.io.BlockGuardOs.open(BlockGuardOs.java:206)
       at libcore.io.IoUtils.canOpenReadOnly(IoUtils.java:163)
       at dalvik.system.DexPathList$NativeLibraryElement.findNativeLibrary(DexPathList.java:833)
       at dalvik.system.DexPathList.findLibrary(DexPathList.java:548)
       at dalvik.system.BaseDexClassLoader.findLibrary(BaseDexClassLoader.java:179)
       at java.lang.Runtime.loadLibrary0(Runtime.java:1005)
       at java.lang.System.loadLibrary(System.java:1669)
       at com.facebook.soloader.nativeloader.SystemDelegate.loadLibrary(SystemDelegate.java:24)
       at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:52)
       at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:30)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:774)
       at com.facebook.flipper.android.FlipperClientImpl.<clinit>(FlipperClientImpl.java:26)
       at com.facebook.flipper.android.FlipperClientImpl.init(FlipperClientImpl.java)
       at com.facebook.flipper.android.AndroidFlipperClient.getInstance(AndroidFlipperClient.java:52)
       at com.mobile.app.DebugTools.onApplicationCreated(DebugTools.kt:70)
       at com.mobile.app.DebugApplication.onCreate(DebugApplication.kt:24)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1158)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6271)
       at android.app.ActivityThread.access$1200(ActivityThread.java:238)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7099)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) 
```
**Device: Samsung Galaxy A50
Operating system: Android 9**

**Comment by Pisilay9** [comment]
app market
