### ISSUE TITLE
Library load fails if thread receives interrupt

### ISSUE THREAD

**Issue by Sk1talec** [facebook/SoLoader#14]
Exception: java.nio.channels.ClosedByInterruptException
       at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:113)
       at java.nio.FileChannelImpl.readImpl(FileChannelImpl.java:311)
       at java.nio.FileChannelImpl.read(FileChannelImpl.java:274)
       at com.facebook.soloader.MinElf.read(SourceFile:254)
       at com.facebook.soloader.MinElf.getu32(SourceFile:276)
       at com.facebook.soloader.MinElf.extract_DT_NEEDED(SourceFile:73)
       at com.facebook.soloader.MinElf.extract_DT_NEEDED(SourceFile:48)
       at com.facebook.soloader.DirectorySoSource.getDependencies(SourceFile:113)
       at com.facebook.soloader.DirectorySoSource.loadDependencies(SourceFile:95)
       at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(SourceFile:73)
       at com.facebook.soloader.DirectorySoSource.loadLibrary(SourceFile:52)
       at com.facebook.soloader.ApplicationSoSource.loadLibrary(SourceFile:81)
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SourceFile:636)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SourceFile:547)
       at com.facebook.soloader.SoLoader.loadLibrary(SourceFile:2484)
       at com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.load(SourceFile:40)
       at com.facebook.imagepipeline.memory.NativeMemoryChunk.(SourceFile:31)
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.free(SourceFile:18)
       at com.facebook.imagepipeline.memory.BasePool.get(SourceFile:255)
       at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.(SourceFile:49)
       at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newOutputStream(SourceFile:1139)
       at com.facebook.imagepipeline.producers.NetworkFetchProducer.onResponse(SourceFile:88)
       at com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onResponse(SourceFile:68)
       at com.example.download
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
       at java.util.concurrent.FutureTask.run(FutureTask.java:234)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:856)

We faced a lot of crashes in Fresco: 
Exception: java.lang.NoClassDefFoundError: com/facebook/imagepipeline/memory/NativeMemoryChunk
So we added our own logs in SoLoader. It turns out it won't properly handle Thread#interrupt() while loading libraries. We patched our custom NetworkFetcher to avoid sending such interrupts but maybe it's not desired behavior for SoLoader either.

**Comment by simpleton** [comment]
can you upgrade your soloader to the latest(v0.10.3)?
