### ISSUE TITLE
SoLoader ZipException: Not a zip archive

### ISSUE THREAD

**Issue by ankit-w** [facebook/SoLoader#17]
Hi,
We are getting a crash due to SoLoader, which is being used in our react-native app.
This is primarily happening for users on Android 5/6.
We are using SoLoader version 0.5.0

A significant amount of our users (>60k) are facing this issue.
Crash logs:

```
Caused by java.util.zip.ZipException: Not a zip archive
       at java.util.zip.ZipFile.readCentralDir(ZipFile.java:397)
       at java.util.zip.ZipFile.(ZipFile.java:175)
       at java.util.zip.ZipFile.(ZipFile.java:131)
       at com.facebook.soloader.ExtractFromZipSoSource$ZipUnpacker.(ExtractFromZipSoSource.java)
       at com.facebook.soloader.ApkSoSource$ApkUnpacker.(ApkSoSource.java)
       at com.facebook.soloader.ApkSoSource.makeUnpacker(ApkSoSource.java)
       at com.facebook.soloader.UnpackingSoSource.getSoStorePath(UnpackingSoSource.java)
       at com.facebook.soloader.UnpackingSoSource.getSoStorePath(UnpackingSoSource.java)
       at com.facebook.soloader.SoLoader.initSoSources(SoLoader.java)
       at com.facebook.soloader.SoLoader.init(SoLoader.java)
       at com.facebook.soloader.SoLoader.init(SoLoader.java)
       at com.facebook.soloader.SoLoader.init(SoLoader.java)
       at com.facebook.react.ReactInstanceManager.initializeSoLoaderIfNecessary(ReactInstanceManager.java)
       at com.facebook.react.ReactInstanceManager.(ReactInstanceManager.java)
       at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java)
```

Is anyone else also facing this? How do we resolve this?

**Comment by thekirankumar** [comment]
<img width="769" alt="screen shot 2018-10-29 at 8 36 42 
pm" src="https://user-images.githubusercontent.com/2078154/47659188-659d2e80-dbba-11e8-8294-0bf2a3180ce7.png"> Its happening on a range of low end devices, mainly Xiaomi.

**Comment by passy** [comment]
Have you been able to reproduce this? Especially without the method names and line numbers, this looks like it would be pretty tough to track down.

**Comment by ankit-w** [comment]
Unfortunately, we still haven't been able to reproduce this. We are actively trying to do that and will update here if successful.
