### ISSUE TITLE
Fatal Exception: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libimagepipeline.so

### ISSUE THREAD

**Issue by zetbrush** [facebook/SoLoader#29]
[
<img width="1279" alt="screen shot 2019-02-27 at 7 07 38 pm" src="https://user-images.githubusercontent.com/8019003/53500023-ff221180-3ac2-11e9-9161-48e80b88ee7b.png">
](url)
Fatal Exception: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libimagepipeline.so caused by: dlopen failed: "/mnt/expand/7c0f06c2-1644-460f-8533-efe2fb639ade/user/0/com.studio/lib-main/libimagepipeline.so" is 32-bit instead of 64-bit
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SourceFile:703)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SourceFile:564)
       at com.facebook.soloader.SoLoader.loadLibrary(SourceFile:500)
       at com.facebook.soloader.SoLoader.loadLibrary(SourceFile:455)
       at com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.load(SourceFile:40)
       at com.facebook.imagepipeline.memory.NativeMemoryChunk.(SourceFile:31)
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(SourceFile:25)
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(SourceFile:13)
       at com.facebook.imagepipeline.memory.BasePool.get(SourceFile:267)
       at com.facebook.imagepipeline.memory.MemoryPooledByteBufferOutputStream.(SourceFile:51)
       at com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newByteBuffer(SourceFile:73)
       at com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newByteBuffer(SourceFile:24)
       at com.facebook.imagepipeline.cache.BufferedDiskCache.readFromDiskCache(SourceFile:373)
       at com.facebook.imagepipeline.cache.BufferedDiskCache.access$400(SourceFile:35)
       at com.facebook.imagepipeline.cache.BufferedDiskCache$2.call(SourceFile:193)
       at com.facebook.imagepipeline.cache.BufferedDiskCache$2.call(SourceFile:174)
       at bolts.Task$4.run(SourceFile:357)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(SourceFile:51)
       at java.lang.Thread.run(Thread.java:818)

SoLoader version. [0.5.1]

I think this is relevant/cause of https://github.com/facebook/fresco/issues/2296 pls check

**Comment by passy** [comment]
Have you checked which architecture the bundled `.so` actually is?

**Comment by zetbrush** [comment]
@passy its under `lib/armeabi-v7a/libimagepipeline.so`

**Comment by passy** [comment]
So the device is 32bit and the library is 32bit, too, but you get an error that it should be 64bit? Am I getting this right?

**Comment by zetbrush** [comment]
@passy not sure about the OS, but devices have Cortex-A53 cpus, with support  for both AArch32 and AArch64

**Comment by panpanini** [comment]
@zetbrush could you tell me which version of the Android Gradle Plugin you were using?
Recently we ran into a similar issue when updating from AGP `3.2.0` to `3.4.0`. I found that using either AGP `3.3.0` or `3.4.0` would cause this crash, however `3.2.0` would successfully find the .so file

**Comment by karthickmurugesa** [comment]
Same issue I am also facing 
com.facebook.soloader.SoLoader.doLoadLibraryBySoName
SoLoader.java, line 703
**java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libimagepipeline.so caused by: dlopen failed: "/data/data/org.deelchat/lib-main/libimagepipeline.so" is 64-bit instead of 32-bit
Open**

For android gradle plugin 3.3.1 not working if i am downgraded to 3.2.0 its working .Please Facebook fix this issue ASAP. Don't lose the stability of the lib.

**Comment by artemisia** [comment]
I think I found why this bug happened, because the cpu_abi of /data/data/yourpackage/lib and /data/data/yourpackage/lib-main is different.
And why is it different? because ExtractFromZipSoSource.ensureDsos() had a defect.
What defect? There was an assumption that Android OS think you were a 64-bit app when you had both 32-bit and 64-bit so libraries. But, the rule was broken on the OPPO R7sm (Android 5.1.1 ColorOS: V3.0_170510_beta). 

I have fixed the bug on my OPPO by modifying code, I will make a pull request later, expecting to help your guys.

**Comment by zetbrush** [comment]
@panpanini sorry for late response it was `3.3.1`  back then

**Comment by waseefakhtar** [comment]
@artemisia this sounds good! Have you opened a PR for it yet? If not, I'd love to have a look at your modified code.

**Comment by waseefakhtar** [comment]
Regarding the Android Gradle Plugin, we've been using 3.3.2 but noticed the `UnsatisfiedLinkError` only when we started supporting 64-bit. Also, our error is `Fatal Exception: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libnative-imagetranscoder.so caused by: dlopen failed: "/data/data/com.degoo.android/lib-main/libnative-imagetranscoder.so" is 64-bit instead of 32-bit` and not `Fatal Exception: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libimagepipeline.so caused by: dlopen failed: "/mnt/expand/7c0f06c2-1644-460f-8533-efe2fb639ade/user/0/com.studio/lib-main/libimagepipeline.so" is 32-bit instead of 64-bit`.

**Comment by sp00ne** [comment]
Any update on this? We have crashes in our production app currently

**Comment by nanchen2251** [comment]
> I think I found why this bug happened, because the cpu_abi of /data/data/yourpackage/lib and /data/data/yourpackage/lib-main is different.
> And why is it different? because ExtractFromZipSoSource.ensureDsos() had a defect.
> What defect? There was an assumption that Android OS think you were a 64-bit app when you had both 32-bit and 64-bit so libraries. But, the rule was broken on the OPPO R7sm (Android 5.1.1 ColorOS: V3.0_170510_beta).
> 
> I have fixed the bug on my OPPO by modifying code, I will make a pull request later, expecting to help your guys.

We encountered the same problem on OPPO phones, how did you solve it

**Comment by haliquim** [comment]
I ran into the same issue and resolved it by disabling the backup library sources. The generated APK has the proper libraries in the $appPath/lib folder, and libraries with the incorrect source in $appPath/lib-main. The lib-main sources are configured as a backup source, but are tried before the sources in the lib folder. 

You can change this behavior with the initialization flags, and disabling the backup sources resolved the issue:
```
SoLoader.init(application,
    SoLoader.SOLOADER_DISABLE_BACKUP_SOSOURCE & // DISABLE BACKUP SOURCES
   (~SoLoader.SOLOADER_ENABLE_EXOPACKAGE)); // DISABLE EXOPACKAGE
```

**Comment by qasimgit** [comment]
@here
We are using `0.9.0+`  version still getting alot of crashes, any update on this?
SoLoader Version: `0.9.0+` 
React Native Version: 0.66
would appreciate any help on this
Thanks
below is the screen shot of crash logs

<img width="1173" alt="Screenshot 2021-12-23 at 3 21 56 PM" src="https://user-images.githubusercontent.com/55051250/147226534-59362979-f700-4598-bb24-c21ebe4b28df.png">

**Comment by shawnsmsu** [comment]
It sounds like this issue was resolved with the v0.10.3 release based on the release notes. However, I'm still getting crash reports in production for it since upgrading. I did notice though that I only had 
`        configurations.all {
            resolutionStrategy {
                force "com.facebook.soloader:soloader:0.10.3"
			}
		}
`
in build.gradle and did not have 
`dependencies {
    implementation "com.facebook.soloader:soloader:0.10.3+"
`
in app/build.gradle. Not sure if that's an issue so I've since shipped that. Anyone confirm or deny 10.3 resolving the issue for them?
