### ISSUE TITLE
SoLoader-0.1.0 build error

### ISSUE THREAD

**Issue by rhshen** [facebook/SoLoader#36]
BUILD FAILED
Buck wasn't able to parse C:\cygwin64\home\shenrenhao\SoLoader-0.1.0\java\com\facebook\soloader\BUCK:
NameError: name 'project_config' is not defined
Call stack:
  File "C:\cygwin64\home\shenrenhao\Soloader-0.1.0\.buckd\resources\2019.05.06.01\buck_server\buck_parser\profiler.py", line 507, in wrapped
    return func(*args, **kwargs)
  File "C:\cygwin64\home\shenrenhao\SoLoader-0.1.0\java\com\facebook\soloader\BUCK", line 21
    project_config(

This error happened while trying to get dependency '//java/com/facebook/soloader:soloader' of target '//:soloader'

**Comment by rhshen** [comment]
python scripts/fetch_deps.py 

console->

Unable to connect to Buck daemon, restarting it...
Not using buckd because daemon failed to start.
PARSING BUCK FILES: FINISHED IN 1.6s
CREATING ACTION GRAPH: FINISHED IN 0.1s
DOWNLOADED 0 ARTIFACTS, 0.00 BYTES, 0.0% CACHE MISS
BUILDING: FINISHED IN 2.3s (100%) 1/1 JOBS, 0 UPDATED
BUILD SUCCEEDED
Traceback (most recent call last):
  File "scripts/fetch_deps.py", line 40, in <module>
    main()
  File "scripts/fetch_deps.py", line 33, in main
    deps = json.load(f)
  File "C:\Python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by passy** [comment]
Sorry, but I don't know how to debug this on Windows. Will leave this open if someone else wants to help out.

**Comment by rhshen** [comment]
> Sorry, but I don't know how to debug this on Windows. Will leave this open if someone else wants to help out.

I used cygwin to run buck.
build soloader-0.6.0 is ok.

**Comment by rhshen** [comment]
> Sorry, but I don't know how to debug this on Windows. Will leave this open if someone else wants to help out.

I used cygwin to run buck.
build soloader-0.6.0 is ok.
