### ISSUE TITLE
UnsatisfiedLinkError: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: library "/storage/emulated/0/sample/libs/armeabi-v7a/libc++_shared.so" needed or dlopened by "/system/lib/libnativeloader.so" is not accessible for the namespace "classloader-namespace"

### ISSUE THREAD

**Issue by srikanthsunkari** [facebook/SoLoader#37]
Unable to load the so file from the internal storage directory.
		
```
		    --------- beginning of crash
2019-05-15 20:55:36.828 12231-12231/com.sample.preprod E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sample.preprod, PID: 12231
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: library "/storage/emulated/0/sample/libs/armeabi-v7a/libc++_shared.so" needed or dlopened by "/system/lib/libnativeloader.so" is not accessible for the namespace "classloader-namespace"
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
        at com.android.sample.ui.sun.activities.GameRNActivity.loadNativeLibrary(GameRNActivity.java:273)
        at com.android.sample.ui.sun.activities.GameRNActivity.onCreate(GameRNActivity.java:178)
        at android.app.Activity.performCreate(Activity.java:6868)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2676)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2784)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1523)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6238)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
2019-05-15 20:55:37.155 12231-12231/com.sample.preprod I/Process: Sending signal. PID: 12231 SIG: 9
```

**Comment by srikanthsunkari** [comment]
Seems to It is not possible to load the so file from external directory. [https://stackoverflow.com/questions/56046513/how-to-dynamically-load-a-compiled-native-library-into-an-android-application](url).
