### ISSUE TITLE
AppBundle: Sideloaded 32bit app will be crashed on 64bit devices

### ISSUE THREAD

**Issue by ganadist** [facebook/SoLoader#50]
I found another issue related [sideload](https://developer.android.com/guide/app-bundle/sideload-check) with AppBundle(Split Apk format)

1. Sideload app that have only 32bit ABI `split apk format` into 64bit device.
```
$ adb install-multiple base.apk config.armeabi_v7a.apk
$ adb shell dumpsys package your.app.package_name |grep splits
splits=[base, config.armeabi_v7a]
```
2. Open Google Play Store and go to app description, app is update-able even if has same version code.
3. Update app and google play deliver 64bit abi split apk because device is 64bit.
```
$ adb shell dumpsys package your.app.package_name |grep splits
splits=[base, config.arm64_v8a, config.armeabi_v7a]
```
4. SoLoader raise java.lang.UnsatisfiedLinkError
```
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libyoga.so caused by: couldn't find DSO to load: libfb.so caused by: dlopen failed: "/data/data/your.app.package_name/lib-1/libfb.so" is 32-bit instead of 64-bit
at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:774)
at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:627)
at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:565)
at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:513)
at com.facebook.yoga.YogaNative.<clinit>(YogaNative.java:15)
```

**Comment by simpleton** [comment]
Version 0.10.3 has been released which includes this fix.
