### ISSUE TITLE
Caused by java.io.IOException: Resource deadlock would occur

### ISSUE THREAD

**Issue by tuke0919** [facebook/SoLoader#64]
We are using Fresco, and  initialize it in` Application.onCreate()`.During initialization Fresco initilizes SoLoader, and in some cases SoLoader initialization fails `Could not initialise SoLoader`
Fresco version: 2.0.0
Crashlytics with the following error:
```
Caused by java.io.IOException: Resource deadlock would occur
       at sun.nio.ch.FileDispatcherImpl.lock0(FileDispatcherImpl.java)
       at sun.nio.ch.FileDispatcherImpl.lock(FileDispatcherImpl.java:115)
       at sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1097)
       at java.nio.channels.FileChannel.lock(FileChannel.java:1053)
       at com.facebook.soloader.FileLocker.<init>(FileLocker.java:38)
       at com.facebook.soloader.FileLocker.lock(FileLocker.java:31)
       at com.facebook.soloader.UnpackingSoSource.prepare(UnpackingSoSource.java:417)
       at com.facebook.soloader.SoLoader.initSoSources(SoLoader.java:304)
       at com.facebook.soloader.SoLoader.init(SoLoader.java:181)
       at com.facebook.soloader.SoLoader.init(SoLoader.java:164)
       at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:68)
       at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:45)
       at com.netease.vopen.app.VopenApplicationLike.initFresco(VopenApplicationLike.java:535)
       at com.netease.vopen.app.VopenApplicationLike.onCreate(VopenApplicationLike.java)
       at com.tencent.tinker.entry.TinkerApplicationInlineFence.onCreateImpl_$noinline$(TinkerApplicationInlineFence.java:99)
       at com.tencent.tinker.entry.TinkerApplicationInlineFence.onCreate(TinkerApplicationInlineFence.java:110)
       at com.tencent.tinker.loader.app.TinkerApplication.onCreate(TinkerApplication.java:153)
       at com.netease.nis.wrapper.MyApplication.onCreate(MyApplication.java:24)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1162)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
       at android.app.ActivityThread.access$2000(ActivityThread.java:273)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2020)
       at android.os.Handler.dispatchMessage(Handler.java:112)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

**Comment by Desintegrator** [comment]
same issue. Did you find a solution?
