### ISSUE TITLE
java.lang.VerifyError: com/facebook/i/k at SoLoader.initImpl$230dc011(SoLoader.java:203)

### ISSUE THREAD

**Issue by gajicm93** [facebook/SoLoader#7]
### Description

I posted the exact same issue to Fresco (https://github.com/facebook/fresco/issues/2039), but I believe that it's actually for you.

Crash is happening on Android 4.x devices, when APK is built with ProGuard enabled and 'proguard-android-optimize.txt' configuration file.

### Reproduction

1. Get an Android 4.x device
2. Build an app with following build settings ("-optimize" is the important part):
```
debug {
    minifyEnabled true
    proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro', 'proguard-fresco.pro'
}
```
3. BOOM!

You can find all the detailed information and system dumps here: http://crashes.to/s/c450feed2e9

### Additional Information

* Fresco version: 1.8.0
* Platform version: Android 4.x.

**Comment by passy** [comment]
Hm, not quite sure how soloader itself would be responsible for this. This looks like a proguard issue to me. I reckon this is the line triggering it; it is also the only one explicitly for <= 4.2:

https://github.com/facebook/SoLoader/blob/357c96e5c1d75884770d3e0147e31a70035090d5/java/com/facebook/soloader/SoLoader.java?utf8=%E2%9C%93#L202

You probably want to whitelist this class from Proguard optimizations.

**Comment by gajicm93** [comment]
That's not it, for the following reasons:

1. Happening on 4.4. too
2. Working properly with ProGuard, but with normal 'proguard-android.txt' configuration
3. Works fine on ART, even with optimizations.

**Comment by gajicm93** [comment]
https://stackoverflow.com/a/16634043/4695418

This might very well be a Dalvik bug if you're using or depending on some Java 1.7 code, but you'll have to try reproduce it, and eventually find a way around it.. Or file a bug with ProGuard if there might be the issue, whatever..

**Comment by lambdapioneer** [comment]
@passy I'm handling this bug for the Fresco (see https://github.com/facebook/fresco/issues/2039 for details). Root cause is that ProGuard needs to know about the `DoNotOptimize` annotation. I'll add you to the diff for further discussion.

**Comment by gajicm93** [comment]
@tuncaulubilge It was fixed in Fresco just by updating ProGuard rules.. If you're working directly with SoLoader and facing this problem, try with Frescos ProGuard rules.

**Comment by tuncaulubilge** [comment]
Adding these rules has resolved the issue for me
 
```
-keep,allowobfuscation @interface com.facebook.soloader.DoNotOptimize
-keep class com.facebook.soloader.SysUtil$LollipopSysdeps {
    public <methods>;
}
-keep @com.facebook.soloader.DoNotOptimize class *
-keepclassmembers class * {
    @com.facebook.soloader.DoNotOptimize *;
}
```

**Comment by fenglu09** [comment]
@tuncaulubilge 
Not working for me.

Environment：
RN 48.0.3, 
Android buildToolsVersion: 25.0.0
Android targetSdkVersion 22

**Comment by kceb** [comment]
Not working for me either.

```
I/dalvikvm( 7047): Could not find method com.facebook.soloader.SysUtil.getSupportedAbis, referenced from method com.facebook.soloader.SoLoader.areSoSourcesAbisSupported
W/dalvikvm( 7047): VFY: unable to resolve static method 885: Lcom/facebook/soloader/SysUtil;.getSupportedAbis ()[Ljava/lang/String;
D/dalvikvm( 7047): VFY: replacing opcode 0x71 at 0x0019
W/dalvikvm( 7047): VFY: unable to find class referenced in signature ([Lcom/facebook/soloader/SoSource;)
I/dalvikvm( 7047): Could not find method com.facebook.soloader.Api18TraceUtils.beginTraceSection, referenced from method com.facebook.soloader.SoLoader.doLoadLibraryBySoName
W/dalvikvm( 7047): VFY: unable to resolve static method 838: Lcom/facebook/soloader/Api18TraceUtils;.beginTraceSection (Ljava/lang/String;)V
D/dalvikvm( 7047): VFY: replacing opcode 0x71 at 0x0049
W/dalvikvm( 7047): VFY: array-length on non-array
W/dalvikvm( 7047): VFY:  rejecting opcode 0x21 at 0x0060
W/dalvikvm( 7047): VFY:  rejected Lcom/facebook/soloader/SoLoader;.doLoadLibraryBySoName (Ljava/lang/String;ILandroid/os/StrictMode$ThreadPolicy;)V
W/dalvikvm( 7047): Verifier rejected class Lcom/facebook/soloader/SoLoader;
D/AndroidRuntime( 7047): Shutting down VM
W/dalvikvm( 7047): threadid=1: thread exiting with uncaught exception (group=0xacd87b20)
D/gralloc_ranchu( 1171): gralloc_alloc: Creating ashmem region of size 3768320
E/AndroidRuntime( 7047): FATAL EXCEPTION: main
E/AndroidRuntime( 7047): Process: com.test, PID: 7047
E/AndroidRuntime( 7047): java.lang.VerifyError: com/facebook/soloader/SoLoader
E/AndroidRuntime( 7047): 	at com.test.MainApplication.onCreate(MainApplication.java:49)
E/AndroidRuntime( 7047): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
E/AndroidRuntime( 7047): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4344)
E/AndroidRuntime( 7047): 	at android.app.ActivityThread.access$1500(ActivityThread.java:135)
E/AndroidRuntime( 7047): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
E/AndroidRuntime( 7047): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 7047): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 7047): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
E/AndroidRuntime( 7047): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 7047): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 7047): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
E/AndroidRuntime( 7047): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
E/AndroidRuntime( 7047): 	at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager( 1595):   Force finishing activity com.test/.MainActivity
```

**Comment by kceb** [comment]
@fenglu09 I noticed that the issue arose when I enabled multidex for a device with android sdk version 17 (Android 4.2). To resolve the issue, I followed steps here:

https://developer.android.com/studio/build/multidex#java

1. Add `implementation 'com.android.support:multidex:1.0.3'` to dependencies in app/build.gradle
2. In MainApplication.java:
```
import androidx.multidex.MultiDex; // Note: You might need to replace this with: import android.support.multidex.Multidex;
import android.content.Context;
```
3. Add following to MainApplication.java:
```
  @Override
  protected void attachBaseContext(Context base) {
     super.attachBaseContext(base);
     MultiDex.install(this);
  }
```

**Comment by mantlatsalat97-arch** [comment]
https://github.com/facebook/SoLoader/issues/7
