### ISSUE TITLE
NoSuchMethodError: No static method initIfUninitialized

### ISSUE THREAD

**Issue by brewin** [facebook/SoLoader#72]
Upgraded from v0.9.0 to v0.10.0 that was just released and I'm getting this exception:

```
java.lang.NoSuchMethodError: No static method initIfUninitialized(Lcom/facebook/soloader/nativeloader/NativeLoaderDelegate;)V in class Lcom/facebook/soloader/nativeloader/NativeLoader; or its super classes (declaration of 'com.facebook.soloader.nativeloader.NativeLoader' appears in /data/app/~~ivLCLeJYCuhE2OY1efrd8g==/com.package.debug-YR8Aip3Rut-AZ3MRirDuGw==/base.apk)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:208)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:189)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:217)
```

**Comment by passy** [comment]
Sorry, my bad. 0.10.1 has this fixed.
