### ISSUE TITLE
android.system.ErrnoException on Android 10 and 11

### ISSUE THREAD

**Issue by brewin** [facebook/SoLoader#74]
I'm getting crash reports for an app using SoLoader v0.10.1. The reports are coming from devices running Android 10 and 11. The app is published as an AAB (Android App Bundle), which may or may not be related to the problem. I'm wondering if these exceptions are happening when users try to install the app on an incompatible architecture as described in [this comment](https://github.com/realm/realm-java/issues/5977#issuecomment-401036941). So this might not be a bug, but I don't know for sure. All the reports are from new high-end devices like the Galaxy S21, which might indicate that the users are technically savvy enough to sideload APKs.

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.handleMakeApplication (ActivityThread.java:7469)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:7405)
  at android.app.ActivityThread.access$1500 (ActivityThread.java:301)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2130)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8456)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:596)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
Caused by: java.lang.RuntimeException: 
  at com.facebook.soloader.SoLoader.init (SoLoader.java:12)
  at com.mypackage.App.setupMapbox (App.java:12)
  at com.mypackage.App.onCreate (App.java:15)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1192)
  at android.app.ActivityThread.handleMakeApplication (ActivityThread.java:7464)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:7405)
  at android.app.ActivityThread.access$1500 (ActivityThread.java:301)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2130)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8456)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:596)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
Caused by: java.io.FileNotFoundException: 
  at libcore.io.IoBridge.open (IoBridge.java:492)
  at java.io.FileOutputStream.<init> (FileOutputStream.java:236)
  at java.io.FileOutputStream.<init> (FileOutputStream.java:186)
  at com.facebook.soloader.FileLocker.<init> (FileLocker.java:5)
  at com.facebook.soloader.FileLocker.lock (FileLocker.java:3)
  at com.facebook.soloader.UnpackingSoSource.prepare (UnpackingSoSource.java:3)
  at com.facebook.soloader.SoLoader.initSoSources (SoLoader.java:7)
  at com.facebook.soloader.SoLoader.init (SoLoader.java:4)
  at com.facebook.soloader.SoLoader.init (SoLoader.java:4)
  at com.facebook.soloader.SoLoader.init (SoLoader.java:4)
  at com.mypackage.App.setupMapbox (App.java:4)
  at com.mypackage.App.onCreate (App.java:15)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1192)
  at android.app.ActivityThread.handleMakeApplication (ActivityThread.java:7464)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:7405)
  at android.app.ActivityThread.access$1500 (ActivityThread.java:301)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2130)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8456)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:596)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
Caused by: android.system.ErrnoException: 
  at libcore.io.Linux.open (Linux.java)
  at libcore.io.ForwardingOs.open (ForwardingOs.java:166)
  at libcore.io.BlockGuardOs.open (BlockGuardOs.java:254)
  at libcore.io.ForwardingOs.open (ForwardingOs.java:166)
  at android.app.ActivityThread$AndroidOs.open (ActivityThread.java:8317)
  at libcore.io.IoBridge.open (IoBridge.java:478)
  at java.io.FileOutputStream.<init> (FileOutputStream.java:236)
  at java.io.FileOutputStream.<init> (FileOutputStream.java:186)
  at com.facebook.soloader.FileLocker.<init> (FileLocker.java:5)
  at com.facebook.soloader.FileLocker.lock (FileLocker.java:3)
  at com.facebook.soloader.UnpackingSoSource.prepare (UnpackingSoSource.java:3)
  at com.facebook.soloader.SoLoader.initSoSources (SoLoader.java:7)
  at com.facebook.soloader.SoLoader.init (SoLoader.java:4)
  at com.facebook.soloader.SoLoader.init (SoLoader.java:4)
  at com.facebook.soloader.SoLoader.init (SoLoader.java:4)
  at com.mypackage.App.setupMapbox (App.java:4)
  at com.mypackage.App.onCreate (App.java:15)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1192)
  at android.app.ActivityThread.handleMakeApplication (ActivityThread.java:7464)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:7405)
  at android.app.ActivityThread.access$1500 (ActivityThread.java:301)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2130)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8456)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:596)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
```

**Comment by juanamd** [comment]
I'm experiencing the same issue also on Android version 10 and 11, mostly on Samsung devices, and with SoLoader v0.10.1.

Based on the stack trace, it seems it's related to the creation of the FileOutputStream inside the FileLocker class when using the **dso_lock** file.
I'm no expert on Android, but it seems weird since it's writing to an internal storage dir, right? But it still throws a permission denied error.

Here is the stack trace (redacted app name):
```
java.lang.RuntimeException: Unable to create application com.example.myapp.MainApplication: java.lang.RuntimeException: java.io.FileNotFoundException: /data/user/0/com.example.myapp/lib-0/dso_lock: open failed: EACCES (Permission denied)
        at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7132)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7077)
        at android.app.ActivityThread.access$1500(ActivityThread.java:273)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2096)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8107)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: /data/user/0/com.example.myapp/lib-0/dso_lock: open failed: EACCES (Permission denied)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:219)
        at com.example.myapp.MainApplication.onCreate(MainApplication.java:54)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
        at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7127)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7077)
        at android.app.ActivityThread.access$1500(ActivityThread.java:273)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2096)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8107)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

Caused by: java.io.FileNotFoundException: /data/user/0/com.example.myapp/lib-0/dso_lock: open failed: EACCES (Permission denied)
        at libcore.io.IoBridge.open(IoBridge.java:496)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
        at com.facebook.soloader.FileLocker.<init>(FileLocker.java:36)
        at com.facebook.soloader.FileLocker.lock(FileLocker.java:32)
        at com.facebook.soloader.UnpackingSoSource.prepare(UnpackingSoSource.java:430)
        at com.facebook.soloader.SoLoader.initSoSources(SoLoader.java:327)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:207)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:189)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:217)
        at com.example.myapp.MainApplication.onCreate(MainApplication.java:54)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
        at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7127)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7077)
        at android.app.ActivityThread.access$1500(ActivityThread.java:273)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2096)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8107)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Linux.open(Linux.java:-2)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7984)
        at libcore.io.IoBridge.open(IoBridge.java:482)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
        at com.facebook.soloader.FileLocker.<init>(FileLocker.java:36)
        at com.facebook.soloader.FileLocker.lock(FileLocker.java:32)
        at com.facebook.soloader.UnpackingSoSource.prepare(UnpackingSoSource.java:430)
        at com.facebook.soloader.SoLoader.initSoSources(SoLoader.java:327)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:207)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:189)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:217)
        at com.example.myapp.MainApplication.onCreate(MainApplication.java:54)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
        at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7127)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7077)
        at android.app.ActivityThread.access$1500(ActivityThread.java:273)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2096)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8107)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by nes123** [comment]
Experiencing the same exact problem with Andriod 10 and 11. Any new insights on that? it started after upgrading react-native from 0.62 to 0.64.0

**Comment by brewin** [comment]
I still don't know what causes this, but I worked around the issue by using the system loader when SoLoader fails. I started using SoLoader because the system loader was causing crashes on some devices. Using them both seems to have resolved all issues related to loading the native library, or at least I'm no longer getting any crash reports.

This code will be slightly different depending on what native library you're trying to load. `LibraryLoader` is part of the Mapbox SDK.

```kotlin
        val useSoLoader = try {
            SoLoader.init(this, false)
            true
        } catch (e: Exception) {
            false
        }
        LibraryLoader.setLibraryLoader(object : LibraryLoader() {
            override fun load(name: String?) {
                if (useSoLoader) {
                    try {
                        SoLoader.loadLibrary(name!!)
                    } catch (e: Exception) {
                        System.loadLibrary(name!!)
                    }
                } else {
                    System.loadLibrary(name!!)
                }
            }
        })
```

**Comment by juanamd** [comment]
Thanks for sharing your workaround @brewin .
I have some questions though. Are you using react native or is it a native Android app?
I'm trying to figure how would this apply to MainApplication.onCreate() since I cannot see that the "load" function would get called anywhere.
From what I understand SoLoader.init would already load each library on its own right?

**Comment by brewin** [comment]
> I have some questions though. Are you using react native or is it a native Android app?
It's a native Android app.
> I'm trying to figure how would this apply to MainApplication.onCreate() since I cannot see that the "load" function would get called anywhere.
> From what I understand SoLoader.init would already load each library on its own right?
Unless React Native has a way to set the library loader like Mapbox does, you probably can't use this workaround.

**Comment by nes123** [comment]
It is becoming a big issue in our application which is in production. Did anyone manage to find a workaround?

Is it essential to include soloader for react-native apps? is there an alternative?

**Comment by nes123** [comment]
Any help with that will be very much appreciated :)

**Comment by pedrolopes10** [comment]
This error also happens on Android 12 and I have more than 2k crashes related to this and a lots of bad reviews. Any updates?

@wildseansy did it solve?

Thanks

**Comment by wildseansy** [comment]
Still in our release pipeline, releasing thurs-fri, will keep posted

**Comment by pedrolopes10** [comment]
Hi guys just an update:

The File setWritable solution didn't work for me. With the new soloader 0.10.2 worked on Android 12 but now I'm facing new errors on my phone.

**Comment by jamsch** [comment]
Not working here either. Might be that the "dso_lock" file may not exist and we'd need to create it?

**Comment by pedrolopes10** [comment]
With soloader 0.10.3 issue is fixed! Nice work!

**Comment by rocketlanguages** [comment]
> With soloader 0.10.3 issue is fixed! Nice work!

Nice! Will be pushing out a new release for my React Native app with the following to see if anything has changed.

```groovy
// android/app/build.gradle
configurations.all {
     resolutionStrategy {
       force "com.facebook.soloader:soloader:0.10.3"
     }
}
```

**Comment by jamsch** [comment]
>With soloader 0.10.3 issue is fixed! Nice work!

That's hopeful to hear. Pushing out a new release of my React Native app with the following

```groovy
// android/app/build.gradle
configurations.all {
     resolutionStrategy {
       force "com.facebook.soloader:soloader:0.10.3"
     }
}
```

**Comment by mym0404** [comment]
Gradle force versioning is deprecated [link](https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html)
You can use strict versioning
```groovy
    implementation('com.facebook.soloader:soloader:0.10.3') {
        version {
            strictly '0.10.3'
        }
    }
    implementation('com.facebook.soloader:annotation:0.10.3') {
        version {
            strictly '0.10.3'
        }
    }
    implementation('com.facebook.soloader:nativeloader:0.10.3') {
        version {
            strictly '0.10.3'
        }
    }
```

**Comment by jamsch** [comment]
> Gradle force versioning is deprecated [link](https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html) You can use strict versioning

Thanks for letting me know! Will do.

**Comment by mym0404** [comment]
But I don't know strict version for `annotation`, `nativeloader` also needed. I just fixed all soloader related libraries in gradle dependencies.

**Comment by wildseansy** [comment]
I think you can even just update your [gradle.properties](https://github.com/facebook/react-native/blob/1465c8f3874cdee8c325ab4a4916fda0b3e43bdb/ReactAndroid/gradle.properties#L16) to include

```
SO_LOADER_VERSION=0.10.3
```

**Comment by simpleton** [comment]
I will close this issue due to 0.10.3 should fix the crash. let me know if it doesn't work. thanks guys.

**Comment by wildseansy** [comment]
Updating `gradle.properties` didn't actually correctly updeate the version for my project.  There may be a RN node_modules dependency that might be overriding it, I'm not totally sure.  This is what I did to resolve the version for my project

```gradle
// gradle.properties
SO_LOADER_VERSION=0.10.3

// app/build.gradle
configurations.all {
    resolutionStrategy {
        eachDependency { details ->
            if (details.requested.group == 'com.facebook.soloader') {
                //https://github.com/facebook/SoLoader/issues/74#issuecomment-961986593
                switch (details.requested.name) {
                    case 'soloader':
                        details.useVersion SO_LOADER_VERSION
                        break
                }
            }
        }
    }
}
```

> Pretty sure you can just update your [gradle.properties](https://github.com/facebook/react-native/blob/1465c8f3874cdee8c325ab4a4916fda0b3e43bdb/ReactAndroid/gradle.properties#L16) to include
> 
> ```
> SO_LOADER_VERSION=0.10.3
> ```
> 
> This was helpful for me too, seeing the changes: https://github.com/facebook/SoLoader/releases
> 
> Thanks for flagging the new release @mym0404 🙏

**Comment by MuhammadRafeh** [comment]
> 

in the file where to put this code?

**Comment by wildseansy** [comment]
@MuhammadRafeh in your Android `app/build.gradle`
