### ISSUE TITLE
Android app bundle crashes of soloader

### ISSUE THREAD

**Issue by Desintegrator** [facebook/SoLoader#76]
All of ours Android apps (React-Native) provided with app bundle (.aab) experiencing with much amount of soloader crashes.
Different devices, different OS versions. Can not reproduce it on our testing devices
Switching to separate apps is not an options since starting from August 2021 app bundle is required.

react versions:
```
"react": "17.0.1",
"react-native": "0.64.0", (soloader version 0.9.0 here)
```

Stacktrace 1:
```
java.io.IOException at (Unknown Source)
com.facebook.soloader.g.<init> (or com.facebook.soloader.FileLocker.<init>)
java.lang.RuntimeException: Unable to create application chat.roulette.MainApplication: java.lang.RuntimeException: java.io.IOException: Resource deadlock would occur
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6853)
	at android.app.ActivityThread.access$1400(ActivityThread.java:246)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7876)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.RuntimeException: java.io.IOException: Resource deadlock would occur
	at com.facebook.soloader.SoLoader.g(Unknown Source)
	at chat.roulette.MainApplication.onCreate(Unknown Source)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1193)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6848)
	... 8 more
Caused by: java.io.IOException: Resource deadlock would occur
	at sun.nio.ch.FileDispatcherImpl.lock0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.lock(FileDispatcherImpl.java:115)
	at sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1139)
	at java.nio.channels.FileChannel.lock(FileChannel.java:1053)
	at com.facebook.soloader.g.<init>(Unknown Source)
	at com.facebook.soloader.g.c(Unknown Source)
	at com.facebook.soloader.n.b(Unknown Source)
	at com.facebook.soloader.SoLoader.i(Unknown Source)
	at com.facebook.soloader.SoLoader.f(Unknown Source)
	at com.facebook.soloader.SoLoader.e(Unknown Source)
	at com.facebook.soloader.SoLoader.g(Unknown Source)
	... 11 more
```

Stacktrace 2: (little bit different)
```
java.lang.RuntimeException: Unable to create application chat.roulette.MainApplication: java.lang.RuntimeException: java.io.IOException: Resource deadlock would occur
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5506)
	at android.app.ActivityThread.-wrap2(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6251)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1073)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:934)
Caused by: java.lang.RuntimeException: java.io.IOException: Resource deadlock would occur
	at com.facebook.soloader.SoLoader.g(Unknown Source)
	at chat.roulette.MainApplication.onCreate(Unknown Source)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5503)
	... 8 more
Caused by: java.io.IOException: Resource deadlock would occur
	at sun.nio.ch.FileDispatcherImpl.lock0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.lock(FileDispatcherImpl.java:99)
	at sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1026)
	at java.nio.channels.FileChannel.lock(FileChannel.java:875)
	at com.facebook.soloader.g.<init>(Unknown Source)
	at com.facebook.soloader.g.c(Unknown Source)
	at com.facebook.soloader.n.b(Unknown Source)
	at com.facebook.soloader.SoLoader.i(Unknown Source)
	at com.facebook.soloader.SoLoader.f(Unknown Source)
	at com.facebook.soloader.SoLoader.e(Unknown Source)
	... 12 more
```

**Comment by simpleton** [comment]
Thanks for reporting. do you have the proguard map or symbolicated backtrace?

**Comment by Desintegrator** [comment]
@simpleton I have proguard map located in `build/outputs/mapping/release/mapping.txt` Where should i share it?

**Comment by simpleton** [comment]
You can directly share right here or send to my email simsun[at]fb.com

**Comment by Desintegrator** [comment]
@simpleton sent to your email

**Comment by Desintegrator** [comment]
@simpleton any updates?

**Comment by simpleton** [comment]
@Desintegrator sorry for late reply. I haven't received your email. maybe you can share the mapping snippet in comment? I just wanna de-obfuscate below backtrace. thanks
```
        at com.facebook.soloader.g.<init>(Unknown Source)
	at com.facebook.soloader.g.c(Unknown Source)
	at com.facebook.soloader.n.b(Unknown Source)
	at com.facebook.soloader.SoLoader.i(Unknown Source)
	at com.facebook.soloader.SoLoader.f(Unknown Source)
	at com.facebook.soloader.SoLoader.e(Unknown Source)
	at com.facebook.soloader.SoLoader.g(Unknown Source)
```

**Comment by Desintegrator** [comment]
```
com.facebook.soloader.FileLocker -> com.facebook.soloader.g:
    java.io.FileOutputStream mLockFileOutputStream -> a
    java.nio.channels.FileLock mLock -> b
    com.facebook.soloader.FileLocker lock(java.io.File) -> c


com.facebook.soloader.UnpackingSoSource -> com.facebook.soloader.n:
    android.content.Context mContext -> c
    java.util.Map mLibsBeingLoaded -> e
    java.lang.String mCorruptedLib -> d
    int loadLibrary(java.lang.String,int,android.os.StrictMode$ThreadPolicy) -> a
    void prepare(int) -> b
    void access$000(java.io.File,byte) -> g
    void deleteUnmentionedFiles(com.facebook.soloader.UnpackingSoSource$Dso[]) -> h
    void extractDso(com.facebook.soloader.UnpackingSoSource$InputDso,byte[]) -> i
    byte[] getDepsBlock() -> j
    java.lang.Object getLibraryLock(java.lang.String) -> k
    java.io.File getSoStorePath(android.content.Context,java.lang.String) -> l
    com.facebook.soloader.UnpackingSoSource$Unpacker makeUnpacker() -> m
    void prepare(java.lang.String) -> n
    boolean refreshLocked(com.facebook.soloader.FileLocker,int,byte[]) -> o
    void 


com.facebook.soloader.SoLoader -> com.facebook.soloader.SoLoader:
    boolean isSystemApp -> m
    int sFlags -> l
    com.facebook.soloader.ApplicationSoSource sApplicationSoSource -> g
    java.util.HashSet sLoadedLibraries -> h
    int sSoSourcesVersion -> e
    com.facebook.soloader.UnpackingSoSource[] sBackupSoSources -> f
    java.util.concurrent.locks.ReentrantReadWriteLock sSoSourcesLock -> c
    com.facebook.soloader.SoSource[] sSoSources -> d
    java.util.Set sLoadedAndMergedLibraries -> j
    com.facebook.soloader.SoFileLoader sSoFileLoader -> b
    java.util.Map sLoadingLibraries -> i
    boolean SYSTRACE_LIBRARY_LOADING -> a
    com.facebook.soloader.SystemLoadLibraryWrapper sSystemLoadLibraryWrapper -> k
    void assertInitialized() -> a
    boolean checkIfSystemApp(android.content.Context,int) -> b
    void doLoadLibraryBySoName(java.lang.String,int,android.os.StrictMode$ThreadPolicy) -> c
    java.lang.reflect.Method getNativeLoadRuntimeMethod() -> d
    void init(android.content.Context,int) -> e
    void init(android.content.Context,int,com.facebook.soloader.SoFileLoader) -> f
    void init(android.content.Context,boolean) -> g
    void initSoLoader(com.facebook.soloader.SoFileLoader) -> h
    void initSoSources(android.content.Context,int,com.facebook.soloader.SoFileLoader) -> i
    boolean isInitialized() -> j
    boolean loadLibrary(java.lang.String) -> k
    boolean loadLibrary(java.lang.String,int) -> l
    void loadLibraryBySoName(java.lang.String,int,android.os.StrictMode$ThreadPolicy) -> m
    boolean 
```

Full mapping here: https://drive.google.com/file/d/1oS1BJjqHorOw21SbYKfmjdAR9E-iddom/view?usp=sharing

**Comment by Desintegrator** [comment]
@simpleton any updates?

**Comment by nes123** [comment]
It is becoming a big issue to our application which is in production. Did anyone manage to find a workaround? We started to see the first crashes on May 22, is there an explanation for that?

Is it essential to include soloader for react-native apps? is there an alternative?

**Comment by omarkhaled11** [comment]
Any updates on this? I am getting the exact same issue as well

**Comment by anishsundarjee** [comment]
getting same issue here as well.

**Comment by Desintegrator** [comment]
still waiting for solution

**Comment by nb7123** [comment]
See the issues [REPO](https://github.com/nb7123/soloader-issues)

**Comment by zacdemi** [comment]
Also having this issue.

**Comment by Desintegrator** [comment]
@simpleton hmm, last version stored in maven is 0.10.1 from Jan, 2021. looks not fresh enough

**Comment by simpleton** [comment]
v0.10.3 should address this issue.

**Comment by Jamal-ReachFirst** [comment]
> v0.10.3 should address this issue.

No it didn't, it increases the crash rate
