### ISSUE TITLE
Crash "com.facebook.soloader.SysUtil.dumbDeleteRecursive"

### ISSUE THREAD

**Issue by botevst** [facebook/SoLoader#77]
Starting from May 21, most of our users' devices began to crash with an error:

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:7409)
  at android.app.ActivityThread.access$2400 (ActivityThread.java:251)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2284)
  at android.os.Handler.dispatchMessage (Handler.java:110)
  at android.os.Looper.loop (Looper.java:219)
  at android.app.ActivityThread.main (ActivityThread.java:8393)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:513)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1055)
Caused by: java.lang.RuntimeException: 
  at com.facebook.soloader.SoLoader.init (SoLoader.java:214)
  at com.ultimateguitar.ugpro.MainApplication.onCreate (MainApplication.java:163)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1202)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:7393)
Caused by: java.io.IOException: 
  at com.facebook.soloader.SysUtil.dumbDeleteRecursive (SysUtil.java:119)
  at com.facebook.soloader.UnpackingSoSource.deleteUnmentionedFiles (UnpackingSoSource.java:207)
  at com.facebook.soloader.UnpackingSoSource.regenerate (UnpackingSoSource.java:264)
  at com.facebook.soloader.UnpackingSoSource.refreshLocked (UnpackingSoSource.java:321)
  at com.facebook.soloader.UnpackingSoSource.prepare (UnpackingSoSource.java:414)
  at com.facebook.soloader.SoLoader.initSoSources (SoLoader.java:322)
  at com.facebook.soloader.SoLoader.init (SoLoader.java:200)
  at com.facebook.soloader.SoLoader.init (SoLoader.java:182)
  at com.facebook.soloader.SoLoader.init (SoLoader.java:212)
```

We tested different ideas starting with targetSDKVersion=30 and different versions of the RN. 

- react-native 0.63.3
- Android App Bundle
- Android 9, 10, 11

**Comment by nahuelb** [comment]
Hi, I am having the same issue on my last android release, also around May 21. I have react native 0.64.1.

My stacktrace:
`caused by: java.io.IOException: could not delete: /data/user/0/my.app.name/lib-0/libevent-2.1.so
        at com.facebook.soloader.SysUtil.dumbDeleteRecursive(SysUtil.java:119)
        at com.facebook.soloader.UnpackingSoSource.deleteUnmentionedFiles(UnpackingSoSource.java:207)
        at com.facebook.soloader.UnpackingSoSource.regenerate(UnpackingSoSource.java:264)
        at com.facebook.soloader.UnpackingSoSource.refreshLocked(UnpackingSoSource.java:321)
        at com.facebook.soloader.UnpackingSoSource.prepare(UnpackingSoSource.java:414)
        at com.facebook.soloader.SoLoader.initSoSources(SoLoader.java:322)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:200)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:182)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:212)
        at app.puramente.app.MainApplication.onCreate(MainApplication.java:79)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1158)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6266)
        at android.app.ActivityThread.access$1200(ActivityThread.java:240)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1797)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7094)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)`

Some stuff I realized: 
  - This issue only happens when the user updates the app to the new version, new downloads work fine.
  - If the user having the crash, uninstalls and re-installs the app, the isssue is fixed.
  - If the user having the crash goes to the Android settings and clear the cache of the app, it is also fixed.
  - It also had the issue on react-native 0.64.0

From the previous version of my app to the one having this issue, there were almost no native changes, some crashlytics settings modified and new dependencies, I tried rollbacking those changes but the crash still happens.

I tried a bunch of stuff, like disabling abi splits or forcing a different SoLoader version on my build.gradle , and at some point I noticed that stacktrace changed, it was another file that SoLoader couldn't delete:

First it was:
`caused by: java.io.IOException: could not delete: /data/user/0/my.app.name/lib-0/libevent_core-2.1.so`
Later:
`caused by: java.io.IOException: could not delete: /data/user/0/app.puramente.app/lib-0/libflipper.so`
And now:
`caused by: java.io.IOException: could not delete: /data/user/0/my.app.name/lib-0/libevent-2.1.so`


Not sure if it is helpful, but hope it helps.

**Comment by JeffGuKang** [comment]
It is very critical issue. It is happened when we deploy application with RN version downgrade from 0.66.1 to 0.64.1.

**Comment by hari** [comment]
> It was a very critical issue. It is happened when we deploy application with RN version downgrade from 0.66.1 to 0.64.1.

Happening to our app as well.

**Comment by simpleton** [comment]
is your APP still experiencing this crash on v0.10.3?

**Comment by JeffGuKang** [comment]
> is your APP still experiencing this crash on v0.10.3?
I am not sure. I applied your solution and recommend re install to users a lot. and it looks working well. 
But I am not sure it is happened only when we downgrade RN version to 0.64 from 0.66.

**Comment by 9r4ik** [comment]
same when downgrade from 0.66 to 0.64

**Comment by scarlac** [comment]
@simpleton I had this issue consistently even after rebuilding (without reinstalling).
It was fixed for me by updating (as instructed)[https://github.com/facebook/SoLoader/issues/77#issuecomment-851106960] to v0.10.1. The resolved version seems to v0.10.1, not .3:
```
com.facebook.soloader:annotation:0.10.1
com.facebook.soloader:nativeloader:0.10.1
com.facebook.soloader:soloader:0.10.1@aar
```

**Comment by msharibahmed** [comment]
I am getting the below LOG in my play console account and exactly same thing is happening that you mentioned @botevst
 ->

 **Some stuff I realized:

- Only happens when the user updates the app to the new version, fresh downloads work fine.
- If the user has the crash, uninstalls and re-installs the app, and it works.
- If the user goes to the Android settings and clears the cache of the app, it is also fixed.**

```
Exception java.lang.RuntimeException:
  at android.app.ActivityThread.installProvider (ActivityThread.java:8195)
  at android.app.ActivityThread.installContentProviders (ActivityThread.java:7698)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:7452)
  at android.app.ActivityThread.access$1600 (ActivityThread.java:310)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2277)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at android.app.ActivityThread.main (ActivityThread.java:8633)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:567)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1133)
Caused by androidx.startup.d:
  at androidx.startup.AppInitializer.doInitialize (AppInitializer.java)
  at androidx.startup.AppInitializer.discoverAndInitialize (AppInitializer.java)
  at androidx.startup.InitializationProvider.onCreate (InitializationProvider.java)
  at android.content.ContentProvider.attachInfo (ContentProvider.java:2516)
  at android.content.ContentProvider.attachInfo (ContentProvider.java:2486)
  at android.app.ActivityThread.installProvider (ActivityThread.java:8190)
Caused by java.lang.RuntimeException:
  at com.facebook.soloader.SoLoader.init (SoLoader.java)
  at org.jitsi.meet.sdk.JitsiInitializer.create (JitsiInitializer.java)
  at org.jitsi.meet.sdk.JitsiInitializer.create (JitsiInitializer.java)
  at androidx.startup.AppInitializer.doInitialize (AppInitializer.java)
Caused by java.io.IOException:
  at com.facebook.soloader.SysUtil.dumbDeleteRecursive (SysUtil.java)
  at com.facebook.soloader.UnpackingSoSource.deleteUnmentionedFiles (UnpackingSoSource.java)
  at com.facebook.soloader.UnpackingSoSource.regenerate (UnpackingSoSource.java)
  at com.facebook.soloader.UnpackingSoSource.refreshLocked (UnpackingSoSource.java)
  at com.facebook.soloader.UnpackingSoSource.prepare (UnpackingSoSource.java)
  at com.facebook.soloader.SoLoader.initSoSources (SoLoader.java)
  at com.facebook.soloader.SoLoader.init (SoLoader.java)
  at com.facebook.soloader.SoLoader.init (SoLoader.java)
  at com.facebook.soloader.SoLoader.init (SoLoader.java)
```
