### ISSUE TITLE
ANR at SysUtil on Android 11

### ISSUE THREAD

**Issue by zetbrush** [facebook/SoLoader#90]
getting ANR report on Android 11, for soloader version 10.1

```
main (native): tid=1 systid=28668
#00 pc 0x86f90 libc.so 
#01 pc 0x1b189c libart.so 
#02 pc 0x675ee8 libart.so 
#03 pc 0x675cc4 libart.so 
       at java.io.FileDescriptor.sync(FileDescriptor.java)
       at com.facebook.soloader.SysUtil.fsyncRecursive(SysUtil.java:280)
       at com.facebook.soloader.SysUtil.fsyncRecursive(SysUtil.java:274)
       at com.facebook.soloader.UnpackingSoSource$1.run(UnpackingSoSource.java:377)
       at com.facebook.soloader.UnpackingSoSource.refreshLocked(UnpackingSoSource.java:392)
       at com.facebook.soloader.UnpackingSoSource.prepare(UnpackingSoSource.java:433)
       at com.facebook.soloader.SoLoader.initSoSources(SoLoader.java:327)
       at com.facebook.soloader.SoLoader.init(SoLoader.java:207)
       at com.facebook.soloader.SoLoader.init(SoLoader.java:189)
       at com.facebook.imagepipeline.nativecode.NativeCodeInitializer.init(NativeCodeInitializer.java:24)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:84)
       at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:54)
       at GlobalApplication.initFresco(GlobalApplication.java:629)
       at GlobalApplication.onCreate(GlobalApplication.java:294)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1242)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7218)
       at android.app.ActivityThread.access$1500(ActivityThread.java:269)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2166)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:257)
       at android.app.ActivityThread.main(ActivityThread.java:8218)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
```

**Comment by simpleton** [comment]
can you try the latest version(0.10.3)?
